# Generated by Django 5.1.3 on 2024-11-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drophutApp', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='blog_images'),
        ),
    ]
